In [ ]:
import numpy as np

In [ ]:
mylist = [1, 2, 3, 4, 5]

In [ ]:
type(mylist)

list

In [ ]:
myArray = np.array(mylist)

In [ ]:
myArray

array([1, 2, 3, 4, 5])

In [ ]:
type(myArray)

numpy.ndarray

In [ ]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.zeros(shape=(10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.random.seed(101)

In [ ]:

randomArray = np.random.randint(0, 100, size=(10))
randomArray

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40], dtype=int32)

In [ ]:

randomArray2 = np.random.randint(0, 100, size=(10))
randomArray2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40], dtype=int32)

In [ ]:
randomArray.max()

np.int32(95)

In [ ]:
randomArray.argmax()

np.int64(0)

In [ ]:
randomArray.min()

np.int32(9)

In [ ]:
randomArray.argmin()

np.int64(7)

In [ ]:
randomArray.mean()

np.float64(60.8)

In [ ]:
randomArray.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]], dtype=int32)

In [ ]:
randomArray2.reshape(5,2)

array([[ 4, 63],
       [40, 60],
       [92, 64],
       [ 5, 12],
       [93, 40]], dtype=int32)

In [ ]:
bigArray = np.arange(0,100).reshape(10,10)
bigArray

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
bigArray.shape

(10, 10)

In [ ]:
rowOfInterest = 4
columnOfInterest = 6
bigArray[rowOfInterest, columnOfInterest]

np.int64(46)

In [ ]:
bigArray[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
bigArray[:,1].shape

(10,)

In [ ]:
bigArray[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [ ]:
bigArray[:,1].reshape(1,10)

array([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [ ]:
bigArray[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [ ]:
bigArray[0:3,0:3] = 0
bigArray

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
bigArrayCopy = bigArray.copy()
bigArrayCopy

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])